### ISSUE TITLE
Support glob patterns

### ISSUE THREAD

**Issue by pmkroeker** [teledemic/vscode-branch-warning#1]
Would it be possible to support glob patterns for warnings? Like below?

```typescript
branchwarnings.protectedBranches: ['master', 'release/**']
```

This would help not having to put in each release branch (or subset of branches) each time one is created.

**Comment by ludakhris** [comment]
@pmkroeker I think this is a good idea. Might try and tackle it this week.

**Comment by ludakhris** [comment]
I'll be submitting a pull request today to add this feature. It will allow people to specify other protected branches with a glob pattern. A use case my team will use it for is to warn team members about master or any release branches.

**Comment by ludakhris** [comment]
If this pull request is approved it is labeled to appear in version 1.0.7 of the plugin.
