### ISSUE TITLE
Extension hides and shows branch warnings at the wrong times

### ISSUE THREAD

**Issue by JordanLongstaff** [teledemic/vscode-branch-warning#10]
I just downloaded this extension, and after a bit of experimenting with it, I was not satisfied at all with the timing of its decisions to either hide or show the branch warning. It seems like it never changes when a branch is checked out - _like what's supposed to happen_ - or even if I make changes on any branch or commit said changes. It seems the only time it updates is when the extension settings are changed. This is wrong and needs fixing.

If it helps, I am using extension version 1.0.7 in VS Code 1.46.1 in macOS 10.15.5.

**Comment by ludakhris** [comment]
Yeah that definitely isn't the experience I have and I have nearly the same VSCode version.  

Maybe provide the relevant portion of your settings.xml and maybe some information (if you can) on the git repo your using, maybe that'll shed some light on whats happening

**Comment by JordanLongstaff** [comment]
I can only assume you're talking about my `settings.json` file, which looks like this, except sensitive information has been redacted (and isn't relevant anyway):

```
{
    "editor.codeActionsOnSave": {
        "source.fixAll.tslint": true
    },
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "typescript.updateImportsOnFileMove.enabled": "always",
    "python.venvPath": ...
    "python.envFile": ...
    "python.pythonPath": ...
    "python.formatting.autopep8Args": ["--max-line-length", "128", "--experimental"],
    "python.formatting.blackArgs": ["--line-length", "128"],
    "typescript.preferences.quoteStyle": "double",
    "javascript.preferences.quoteStyle": "double",
    "explorer.confirmDelete": false,
    "javascript.updateImportsOnFileMove.enabled": "always",
    "git.enableSmartCommit": true,
    "markdown.extension.preview.autoShowPreviewToSide": true,
    "vscode-postgres.prettyPrintJSONfields": true,
    "vscode-postgres.defaultConnection": ...
    "vscode-postgres.defaultDatabase": ...
    "ispy.cmdargs.ipython": "",
    "python.dataScience.useDefaultConfigForJupyter": false,
    "python.dataScience.askForKernelRestart": false,
    "python.dataScience.debugJustMyCode": false,
    "[python]": {
        "editor.defaultFormatter": "ms-python.python"
    },
    "typescript.preferences.importModuleSpecifier": "non-relative",
    "pythonTestExplorer.testFramework": "pytest",
    "python.formatting.provider": "black",
    "window.zoomLevel": 0,
    "python.languageServer": "Microsoft",
    "branchwarnings.msgColor": "#ff0",
    "branchwarnings.msgTooltip": "This branch is protected.",
    "branchwarnings.protectedBranches": [
        "master",
        "production",
        "release-candidate"
    ]
}
```

The git repo is used privately by my company, so I don't feel comfortable sharing it with you. All I can tell you is that right now I only have three local branches.

**Comment by ludakhris** [comment]
Yes sorry I did mean your settings.json.

Yeah thats fine, maybe you can also share what directory you have open in vscode wrt to the actual repo (if you don't have the repository root open).

**Comment by JordanLongstaff** [comment]
I don't think that matters so much either, but my IDE workspace contains two folders which are both direct subfolders of my Git repo. There are a bunch of other files and subfolders in the checkout directory of the repo that are left out of the IDE workspace. The workspace file itself is not contained in the checkout directory, it's in the parent directory.

**Comment by teledemic** [comment]
@JordanLongstaff feel free to make a PR

**Comment by ludakhris** [comment]
@JordanLongstaff if you do decide to make a PR, there's a quick start in the project "vsc-extension-quickstart.md" that will help.
