### ISSUE TITLE
Just what I want - but not working :(

### ISSUE THREAD

**Issue by jlongo62** [teledemic/vscode-branch-warning#12]
This is just what I am looking for,
Added extension.
Does not seem to do anything.

In settings I have 
,
    "branchwarnings.protectedBranches": [ "master"  ],
    "branchwarnings.msgTooltip": "WARNING: Branch Is Master",
    "branchwarnings.suppressPopup": true

Bug seems to be the workspace must be in the ROOT folder of the GIt for this to work.
If you set the path of the workspace to point to a sub-folder it does not work.
If you put the wrokspace in a sub-folder it does not work.
Only works if workspace is in root of git and path = '.'

Is this fixable ?

**Comment by teledemic** [comment]
Nested workspace support was theoretically added by #4 - I don't use vscode that way but it should work. Does vscode itself recognize that you are in a git repository?
You do not need any settings at all for this extension, only if you want to override the default behavior

**Comment by NGLocanovic** [comment]
Hi,

i have the exact same issue.
When used with a multible Git Repos in a workspace it does not work as intended.
If I test it with a single Repo inside the workspace it works like a charm.

![image](https://user-images.githubusercontent.com/8858043/148508633-eba654e2-4d92-4280-bb26-76ab44726513.png)

![image](https://user-images.githubusercontent.com/8858043/148508688-f8f41945-34f0-4241-b260-3191c0e734a0.png)
