### ISSUE TITLE
Possible change: Default protected branch "master" to "main"

### ISSUE THREAD

**Issue by es-rene99** [teledemic/vscode-branch-warning#13]
This extension is awesome! Thank you for creating it, I did notice a very small possible change, since branches on GitHub/GitLab now default to main, and even on [Git setup it shows how to configure the default branch to main](https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup), this extension could be updated to use main as default as well.

I will do a pull request about this, let me know if it will be a good modification for the project.

**Comment by teledemic** [comment]
Hm good point! Would 100% not want to remove master from the default, but no reason not to have both now that it is becoming more common. Will take a look, thx!

**Comment by teledemic** [comment]
Tweaked and published 1.0.9. Thanks!
