### ISSUE TITLE
More options

### ISSUE THREAD

**Issue by pbuzdin** [teledemic/vscode-branch-warning#7]
Hi there!

I have few customisation suggestions.

Add option to adjust status bar background color:
```
"branchwarnings.msgBGColor": "#000"
```

Option to adjust status bar prefix for warning:
```
"branchwarnings.warningPrefix": "WARNIN: branch"
```

**Comment by ludakhris** [comment]
Hi @pbuzdin -- It doesn't look like vscode gives us direct access to easily change the background color but I certainly can easily do a pull request for the status bar prefix.

**Comment by teledemic** [comment]
@pbuzdin thanks for the input - why is it useful to change the status bar prefix?

**Comment by pbuzdin** [comment]
@teledemic 
red on blue is uncomfortable to watch:
![](https://github.com/teledemic/vscode-branch-warning/blob/master/images/warning.png?raw=true)

If we could change the prefix, then we could put emoji there, like ⚠️.

Ideally it would be better to have an option to put different prefix for each branch.

**Comment by teledemic** [comment]
Thanks - as @ludakhris points out, extensions can't change background colors, that comes from the theme. You can change the foreground color instead using the `msgColor` setting.

**Comment by pbuzdin** [comment]
@teledemic 
I figured out that changing prefix is better then breaking color theme.

**Comment by JordanLongstaff** [comment]
If you don't like red on blue, you can change the text color to something else. I changed it to yellow, which looks fine IMO.

![Screen Shot 2020-06-25 at 4 47 24 PM](https://user-images.githubusercontent.com/7563922/85793887-b5235d00-b703-11ea-9c6c-fab06d0637c4.png)

**Comment by pbuzdin** [comment]
@JordanLongstaff this issue is not about color choice

**Comment by JordanLongstaff** [comment]
> @JordanLongstaff this issue is not about color choice

> Add option to adjust status bar background color:

> red on blue is uncomfortable to watch:

Am I missing something here?

**Comment by pbuzdin** [comment]
@JordanLongstaff [prefix for warning](#issue-637879205)

**Comment by teledemic** [comment]
Closing, irrelevant after #11
