### ISSUE TITLE
Feature: Warn if remote branch exists that matches regex

### ISSUE THREAD

**Issue by Brixomatic** [teledemic/vscode-branch-warning#8]
"branchwarnings.warnIfRemoteBranchExistsMatchingRegex": "release.*"

Basically should do what this does:
git ls-remote --heads | grep "release.*"

**Comment by ludakhris** [comment]
@Brixomatic I'm not sure I understand the use case behind your feature request. Would you mind elaborating?

**Comment by Brixomatic** [comment]
Think of it this way: Say you choose a commit as release candidate, create a new release branch off this commit, like "release1.2.3"  now you want all devs to be aware this branch exists, because some important pull requests should be based on the release candidate, rather than the master branch. You could do this by distributing the vscode settings via git on the master, which is a branch that is regularly observed and merged.

**Comment by ludakhris** [comment]
@Brixomatic Ahh I see thanks for explaining my team uses a similar workflow. However in ours there are a number of branches that exist: release1.2, release1.3, release1.4, wouldn't this message always popup in this case?

**Comment by Brixomatic** [comment]
Our team merges the release branch with all the fixes back to master, oncev the release is released, and then deletes the branch. So in our case it would only appear when a release is being prepared.

**Comment by ludakhris** [comment]
Ahh so the mere presence of one of these branches is enough to warn your team.

**Comment by Brixomatic** [comment]
Yes.

**Comment by ludakhris** [comment]
@Brixomatic I did a pull request to implement this, feedback is welcome.

**Comment by Brixomatic** [comment]
> @Brixomatic I did a pull request to implement this, feedback is welcome.

I've left you review. Looking good!

**Comment by teledemic** [comment]
Thanks for the info, but this feature does not really relate to the purpose of this extension and is a very niche case.

**Comment by teledemic** [comment]
Could certainly be done as a separate extension
